### ISSUE TITLE
Complete the basic tic tac toe

### ISSUE THREAD

**Issue by suffer-sami** [suffer-sami/learning#1]
### Tasks

- [ ] Read [4. More Control Flow Tools](https://docs.python.org/3/tutorial/controlflow.html) 
- [ ] Implement Control Flow Tools in the game
- [ ] Read [5. Data Structures](https://docs.python.org/3/tutorial/datastructures.html)
